<?php
namespace modava\pages\components;

use backend\components\MyController;

class MyPagesController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
